### -------------------------------------------
### TEST 1: LẤY DANH SÁCH (READ)
### -------------------------------------------

### 1.1 Lấy tất cả khóa học (Khi chưa có gì sẽ trả về [])
GET http://localhost:8082/api/courses

### 1.2 Tìm kiếm khóa học (Ví dụ tìm chữ 'Java')
GET http://localhost:8082/api/courses?keyword=Java


### -------------------------------------------
### TEST 2: TẠO KHÓA HỌC (CREATE & VALIDATE)
### -------------------------------------------

### 2.1 Tạo khóa học THÀNH CÔNG (Dữ liệu chuẩn)
# Mong đợi: 200 OK, trả về JSON khóa học
POST http://localhost:8082/api/courses
Content-Type: application/json

{
  "title": "Lập trình Java Spring Boot",
  "description": "Khóa học Backend từ A-Z cho người mới bắt đầu.",
  "price": 500000.0
}

### 2.2 Tạo khóa học THẤT BẠI (Để trống tên)
# Mong đợi: 400 Bad Request - "Tên khóa học không được để trống!"
POST http://localhost:8082/api/courses
Content-Type: application/json

{
  "title": "",
  "description": "Khóa lỗi tên rỗng",
  "price": 100000.0
}

### 2.3 Tạo khóa học THẤT BẠI (Giá tiền âm)
# Mong đợi: 400 Bad Request - "Giá khóa học không được nhỏ hơn 0!"
POST http://localhost:8082/api/courses
Content-Type: application/json

{
  "title": "Khóa học giá âm",
  "description": "Test giá tiền sai",
  "price": -50000.0
}


### -------------------------------------------
### TEST 3: CẬP NHẬT (UPDATE)
### -------------------------------------------

### 3.1 Sửa khóa học ID = 1 (Thành công)
# Mong đợi: 200 OK, Giá đổi thành 900k, Tên đổi thành Advanced
PUT http://localhost:8082/api/courses/3
Content-Type: application/json

{
  "title": "Java Spring Boot Advanced",
  "description": "Cập nhật nội dung nâng cao.",
  "price": 900000.0
}

### 3.2 Sửa khóa học ID = 1 (Thất bại do giá âm)
# Mong đợi: 400 Bad Request
PUT http://localhost:8082/api/courses/3
Content-Type: application/json

{
  "price": -100.0
}


### -------------------------------------------
### TEST 4: XÓA VÀ VÔ HIỆU HÓA (DELETE)
### -------------------------------------------

### 4.1 Ẩn khóa học (Soft Delete)
# Mong đợi: 200 OK, isActive chuyển thành false (Kiểm tra trong DB)
DELETE http://localhost:8082/api/courses/3/deactivate

### 4.2 Lấy chi tiết xem đã bị ẩn chưa
GET http://localhost:8082/api/courses/3

### 4.3 Xóa vĩnh viễn khóa học ID = 1 (Hard Delete)
# Mong đợi: 200 OK
DELETE http://localhost:8082/api/courses/3

### 4.4 Thử xóa khóa học không tồn tại (ID = 9999)
# Mong đợi: 404 Not Found
DELETE http://localhost:8082/api/courses/9999